### PR TITLE
01-3.md translation

### PR DESCRIPTION
**Pull request by titusjgr**

### CODE REVIEW

**Comment by Atcold** [comment]
This is not completed yet, right?

**Comment by titusjgr** [comment]
Yeah, I send the PR in case you want to keep track of the progress.

**Comment by Atcold** [comment]
Oh, okay, so I'm **not** merging for the moment.

**Comment by titusjgr** [comment]
I've done most translation of this chapter. But I have several questions.

- [ ] What does space fabric mean?
- [ ] What does the term vector in the section "Data visualization - separating points by color using a network" mean?

Also, an equation doesn't render so I opened an [issue](https://github.com/Atcold/pytorch-Deep-Learning/issues/75#issue-571908319) in the main repository.

**Comment by Atcold** [comment]
Haha, about "space fabric"... It's an analogy I make, vaguely connecting to cosmology. See https://en.wikipedia.org/wiki/The_Fabric_of_the_Cosmos#Part_III:_Spacetime_and_Cosmology.

You are correct, there are no vectors in figure 1(b).
I'm updating both figures now. You will see some arrows soon.

**Comment by Atcold** [comment]
Done, now the spirals look much better.
Screenshot 2020-02-29 18 26 43

**Comment by titusjgr** [comment]
My translation is complete now.

**Comment by Atcold** [comment]
Can you send your PR to the main repo https://github.com/Atcold/pytorch-Deep-Learning?

**Pull request closed without merging**
